apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gpu-metrics-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-metrics-exporter.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.dcgmExporter.enabled }}
    ignore-check.kube-linter.io/privileged-container: "This daemon set needs to run DCGM Exporter as privileged to access the GPU metrics."
    ignore-check.kube-linter.io/run-as-non-root: "This daemon set needs to run DCGM Exporter as root to access the GPU metrics."
    ignore-check.kube-linter.io/privilege-escalation-container: "This daemon set needs escalate privileges for DCGM Exporter to access the GPU metrics."
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gpu-metrics-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpu-metrics-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gpu-metrics-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.dcgmExporter.enabled }}
        - name: {{- include "dcgm-exporter.config-map" . | indent 1 }}
          configMap:
            name: {{- include "dcgm-exporter.config-map" . | indent 1 }}
        - name: nvidia-install-dir-host
          hostPath:
            path: /home/kubernetes/bin/nvidia
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        {{- end }}
      {{- with .Values.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        - operator: "Exists"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.gpuMetricsExporter.securityContext | nindent 12 }}
          image: "{{ .Values.gpuMetricsExporter.image.repository }}:{{ .Values.gpuMetricsExporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gpuMetricsExporter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          envFrom:
            - configMapRef:
                name: {{- include "gpu-metrics-exporter.config-map" . | indent 1}}
          {{- if .Values.dcgmExporter.enabled}}
          env:
            - name: "DCGM_HOST"
              value: "localhost"
          {{- end }}
          resources:
            {{- toYaml .Values.gpuMetricsExporter.resources | nindent 12 }}
          {{- with .Values.gpuMetricsExporter.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.dcgmExporter.enabled }}
        - name: dcgm-exporter
          image: "{{ .Values.dcgmExporter.image.repository}}:{{ .Values.dcgmExporter.image.tag }}"
          imagePullPolicy: {{ .Values.dcgmExporter.image.pullPolicy }}
          command: [ "/bin/bash", "-c" ]
          args:
          {{- if .Values.dcgmExporter.useExternalHostEngine }}
            - hostname $NODE_NAME; dcgm-exporter --remote-hostengine-info $(NODE_IP) --collectors /etc/dcgm-exporter/counters.csv
          {{- else }}
            - hostname $NODE_NAME; dcgm-exporter --collectors /etc/dcgm-exporter/counters.csv
          {{- end }}
          ports:
            - name: metrics
              containerPort: 9400
          securityContext:
            {{- toYaml .Values.dcgmExporter.securityContext | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: "DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE"
              value: "device-name"
            - name: LD_LIBRARY_PATH
              value: /usr/local/nvidia/lib64
            - name: DCGM_EXPORTER_KUBERNETES
              value: 'true'
            - name: DCGM_EXPORTER_LISTEN
              value: ':9400'
            - name: DCGM_EXPORTER_INTERVAL
              value: '5000'
            {{- with .Values.dcgmExporter.additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{- include "dcgm-exporter.config-map" . | indent 1 }}
              mountPath: "/etc/dcgm-exporter"
              readOnly: true
            - name: nvidia-install-dir-host
              mountPath: /usr/local/nvidia
            - name: pod-resources
              mountPath: /var/lib/kubelet/pod-resources
        {{- end }}
