apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- include "gpu-metrics-exporter.config-map" . | indent 1}}
data:
{{- with .Values.gpuMetricsExporter.config }}
  {{- toYaml . | nindent 2 }}
{{- end }}
