version: "2"

linters:
  default: none
  enable:
    - dogsled
    - revive
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - errname
    - dupword
    - containedctx
    - durationcheck
    - errorlint
  settings:
    mnd:
      checks: [argument, case, condition, return]
    govet:
      disable:
        - shadow
    lll:
      line-length: 200
    misspell:
      locale: US
    revive:
      rules:
        - {name: redefines-builtin-id, disabled: true}
        - {name: nested-structs,     disabled: true}
  exclusions:
    paths:
      - gen
      - e2e

    rules:
      - path: _test\.go
        linters: [gomnd, bodyclose, gosec]
      - linters: [gosec]
        text: G107
      - linters: [unparam]
        text: always receives
      - linters: [revive]
        text: >-
          redundant if ...; err != nil check, just return error instead.

formatters:
  enable:
    - gofmt
    - gci

  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/castai)