// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exporter

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExporter creates a new instance of MockExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExporter {
	mock := &MockExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExporter is an autogenerated mock type for the Exporter type
type MockExporter struct {
	mock.Mock
}

type MockExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExporter) EXPECT() *MockExporter_Expecter {
	return &MockExporter_Expecter{mock: &_m.Mock}
}

// Disable provides a mock function for the type MockExporter
func (_mock *MockExporter) Disable() {
	_mock.Called()
	return
}

// MockExporter_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type MockExporter_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
func (_e *MockExporter_Expecter) Disable() *MockExporter_Disable_Call {
	return &MockExporter_Disable_Call{Call: _e.mock.On("Disable")}
}

func (_c *MockExporter_Disable_Call) Run(run func()) *MockExporter_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExporter_Disable_Call) Return() *MockExporter_Disable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExporter_Disable_Call) RunAndReturn(run func()) *MockExporter_Disable_Call {
	_c.Run(run)
	return _c
}

// Enable provides a mock function for the type MockExporter
func (_mock *MockExporter) Enable() {
	_mock.Called()
	return
}

// MockExporter_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockExporter_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
func (_e *MockExporter_Expecter) Enable() *MockExporter_Enable_Call {
	return &MockExporter_Enable_Call{Call: _e.mock.On("Enable")}
}

func (_c *MockExporter_Enable_Call) Run(run func()) *MockExporter_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExporter_Enable_Call) Return() *MockExporter_Enable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExporter_Enable_Call) RunAndReturn(run func()) *MockExporter_Enable_Call {
	_c.Run(run)
	return _c
}

// Enabled provides a mock function for the type MockExporter
func (_mock *MockExporter) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockExporter_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockExporter_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockExporter_Expecter) Enabled() *MockExporter_Enabled_Call {
	return &MockExporter_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockExporter_Enabled_Call) Run(run func()) *MockExporter_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExporter_Enabled_Call) Return(b bool) *MockExporter_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockExporter_Enabled_Call) RunAndReturn(run func() bool) *MockExporter_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockExporter
func (_mock *MockExporter) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExporter_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockExporter_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExporter_Expecter) Start(ctx interface{}) *MockExporter_Start_Call {
	return &MockExporter_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockExporter_Start_Call) Run(run func(ctx context.Context)) *MockExporter_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExporter_Start_Call) Return(err error) *MockExporter_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExporter_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockExporter_Start_Call {
	_c.Call.Return(run)
	return _c
}
