// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exporter

import (
	"context"

	"github.com/castai/gpu-metrics-exporter/internal/exporter"
	"github.com/castai/gpu-metrics-exporter/pb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricMapper creates a new instance of MockMetricMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricMapper {
	mock := &MockMetricMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricMapper is an autogenerated mock type for the MetricMapper type
type MockMetricMapper struct {
	mock.Mock
}

type MockMetricMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricMapper) EXPECT() *MockMetricMapper_Expecter {
	return &MockMetricMapper_Expecter{mock: &_m.Mock}
}

// Map provides a mock function for the type MockMetricMapper
func (_mock *MockMetricMapper) Map(metrics []exporter.MetricFamilyMap) *pb.MetricsBatch {
	ret := _mock.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for Map")
	}

	var r0 *pb.MetricsBatch
	if returnFunc, ok := ret.Get(0).(func([]exporter.MetricFamilyMap) *pb.MetricsBatch); ok {
		r0 = returnFunc(metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.MetricsBatch)
		}
	}
	return r0
}

// MockMetricMapper_Map_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Map'
type MockMetricMapper_Map_Call struct {
	*mock.Call
}

// Map is a helper method to define mock.On call
//   - metrics []exporter.MetricFamilyMap
func (_e *MockMetricMapper_Expecter) Map(metrics interface{}) *MockMetricMapper_Map_Call {
	return &MockMetricMapper_Map_Call{Call: _e.mock.On("Map", metrics)}
}

func (_c *MockMetricMapper_Map_Call) Run(run func(metrics []exporter.MetricFamilyMap)) *MockMetricMapper_Map_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []exporter.MetricFamilyMap
		if args[0] != nil {
			arg0 = args[0].([]exporter.MetricFamilyMap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricMapper_Map_Call) Return(metricsBatch *pb.MetricsBatch) *MockMetricMapper_Map_Call {
	_c.Call.Return(metricsBatch)
	return _c
}

func (_c *MockMetricMapper_Map_Call) RunAndReturn(run func(metrics []exporter.MetricFamilyMap) *pb.MetricsBatch) *MockMetricMapper_Map_Call {
	_c.Call.Return(run)
	return _c
}

// MapToAvro provides a mock function for the type MockMetricMapper
func (_mock *MockMetricMapper) MapToAvro(ctx context.Context, metrics []exporter.MetricFamilyMap) []exporter.GPUMetric {
	ret := _mock.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for MapToAvro")
	}

	var r0 []exporter.GPUMetric
	if returnFunc, ok := ret.Get(0).(func(context.Context, []exporter.MetricFamilyMap) []exporter.GPUMetric); ok {
		r0 = returnFunc(ctx, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exporter.GPUMetric)
		}
	}
	return r0
}

// MockMetricMapper_MapToAvro_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapToAvro'
type MockMetricMapper_MapToAvro_Call struct {
	*mock.Call
}

// MapToAvro is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []exporter.MetricFamilyMap
func (_e *MockMetricMapper_Expecter) MapToAvro(ctx interface{}, metrics interface{}) *MockMetricMapper_MapToAvro_Call {
	return &MockMetricMapper_MapToAvro_Call{Call: _e.mock.On("MapToAvro", ctx, metrics)}
}

func (_c *MockMetricMapper_MapToAvro_Call) Run(run func(ctx context.Context, metrics []exporter.MetricFamilyMap)) *MockMetricMapper_MapToAvro_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []exporter.MetricFamilyMap
		if args[1] != nil {
			arg1 = args[1].([]exporter.MetricFamilyMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricMapper_MapToAvro_Call) Return(gPUMetrics []exporter.GPUMetric) *MockMetricMapper_MapToAvro_Call {
	_c.Call.Return(gPUMetrics)
	return _c
}

func (_c *MockMetricMapper_MapToAvro_Call) RunAndReturn(run func(ctx context.Context, metrics []exporter.MetricFamilyMap) []exporter.GPUMetric) *MockMetricMapper_MapToAvro_Call {
	_c.Call.Return(run)
	return _c
}
