// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workload

import (
	"context"

	"github.com/castai/gpu-metrics-exporter/internal/workload"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// FindWorkloadForPod provides a mock function for the type MockResolver
func (_mock *MockResolver) FindWorkloadForPod(ctx context.Context, name string, namespace string) (*workload.Workload, error) {
	ret := _mock.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for FindWorkloadForPod")
	}

	var r0 *workload.Workload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*workload.Workload, error)); ok {
		return returnFunc(ctx, name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *workload.Workload); ok {
		r0 = returnFunc(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Workload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolver_FindWorkloadForPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWorkloadForPod'
type MockResolver_FindWorkloadForPod_Call struct {
	*mock.Call
}

// FindWorkloadForPod is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockResolver_Expecter) FindWorkloadForPod(ctx interface{}, name interface{}, namespace interface{}) *MockResolver_FindWorkloadForPod_Call {
	return &MockResolver_FindWorkloadForPod_Call{Call: _e.mock.On("FindWorkloadForPod", ctx, name, namespace)}
}

func (_c *MockResolver_FindWorkloadForPod_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockResolver_FindWorkloadForPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResolver_FindWorkloadForPod_Call) Return(workload1 *workload.Workload, err error) *MockResolver_FindWorkloadForPod_Call {
	_c.Call.Return(workload1, err)
	return _c
}

func (_c *MockResolver_FindWorkloadForPod_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string) (*workload.Workload, error)) *MockResolver_FindWorkloadForPod_Call {
	_c.Call.Return(run)
	return _c
}
